### ISSUE TITLE
AttributeError: 'Output' object has no attribute '_ipython_display_'

### ISSUE THREAD

**Issue by Dhruvil099** [python-streamz/streamz#461]
I am trying to fetch real time updates from mongoDB cluster on Python using streamz PeriodicDataFrame

-------------Start of code----------------------
`import pandas as pd
import numpy as np
import urllib
from streamz.dataframe import PeriodicDataFrame,DataFrame
from streamz import Stream

# import MongoClient from pymongo
from pymongo import MongoClient

# establish a client connection
MONGODB_CONNECTION_STRING = "mongodb+srv://KDRM:"+urllib.parse.quote("pass@123")+"@cluster0.iffy9by.mongodb.net/?retryWrites=true&w=majority"
client = MongoClient(MONGODB_CONNECTION_STRING)

# to check if connection has been established
client.server_info()['ok']

# point to symbolsDB collection 
db = client.symbolsDB

# emtpy symbols collection before inserting new records
db.symbols.drop()

# get all records from collection
symbol_list_from_DB = db.test.find({})

source = pd.DataFrame(list(symbol_list_from_DB))
k=[]

def streamdb(**kwargs):
    no = db.test.count_documents({})
    for i in range(no):
        k.append(pd.Timestamp.now())       
    source['time']= k
    for i in range(no):
        k.pop()
    
    return source.set_index('time')

sdf = PeriodicDataFrame(streamdb,interval='1s')
sdf.tail()`

--------------------------End of code------------------------
![image](https://user-images.githubusercontent.com/106334579/206744940-979afd70-366f-4afa-98c6-145b126df75d.png)

**Comment by martindurant** [comment]
Which version are you using exactly? I seem to recall this problem, there's a chance it is fixed on current master.

**Comment by shenker** [comment]
I believe this is the same issue as https://github.com/python-streamz/streamz/pull/454, I don't think it's fixed on master.

**Comment by martindurant** [comment]
Can you please confirm that the inked PR fixes things for you? I'll merge it, and deal with the lingering CI stuff afterwards.
